type: object
properties:
  name:
    type: string
  vars:
    type: object
    additionalProperties:
      anyOf:
      - type: array
        items:
          type: string
      - enum:
        - boolean
        type: string
  rules:
    type: array
    items:
      type: object
      properties:
        condition:
          type: object
          additionalProperties:
            anyOf:
            - type: array
              items:
                type: string
            - type: string
        action:
          type: string
      required:
      - action
      - condition
required:
- rules
- vars
